#!/usr/bin/env bash

pushd `dirname $0` && DIR=`pwd` && popd

HOST_NCPU=1
if [ -f /proc/cpuinfo ] ; then
    HOST_NCPU=`grep -c processor /proc/cpuinfo`
    [ $HOST_NCPU -lt 1 ] && HOST_NCPU=1
fi

DL_SOURCE="dl_save"
BUILDROOT_DIR="$DIR/buildroot-2012.02"
STAGING_DIR="$DIR/hndtools-arm-linux-2.6.36-uclibc-4.5.3"
CONFIG_FILE="$BUILDROOT_DIR/$DL_SOURCE/defconfig-arm-uclibc"

function config_update()
{
	echo "Update $BUILDROOT_DIR/.config"
	cp -f $CONFIG_FILE $BUILDROOT_DIR/.config
	eval sed -i \
		-e 's:^BR2_STAGING_DIR=.*:BR2_STAGING_DIR=\"$STAGING_DIR\":g' \
		-e 's:^BR2_JLEVEL=.*:BR2_JLEVEL=$HOST_NCPU:g' \
		$BUILDROOT_DIR/.config
}

if [ ! -f "$BUILDROOT_DIR/.config" ] ; then
	config_update
fi

if [ $# = 1 -a "$1" = "update" ] ; then
	config_update
else
	make -C $BUILDROOT_DIR $@
fi
